# Generated by Django 5.2.14 on 2026-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('delivery_time', models.IntegerField()),
            ],
        ),
    ]
